spring:
  application:
    name: identification-admin
  profiles:
    active: dev # 默认为开发环境

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 日期格式
    default-property-inclusion: non_null
    time-zone: GMT+8 # 北京时区


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 执行的sql语句日志输出
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath*:dao/**/*.xml
    - classpath*:mapper/**/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload
      - /batch/export
      - /doc.html

server:
  port: 8666

redis:
  database:
    authority:
      name: 'authority'
      key:
        admin: 'ums:admin'
        resourceList: 'ums:resourceList'
    identification:
      name: 'identification'
      key:
        codeList: 'code:list'
        whiteCode: 'whiteList:code'
        blackCode: 'blackList:code'
        visitor: 'visit:visitor'
        visitRecord: 'visit:visitRecord'
  expire:
    common: 86400 # 24小时

littlebob:
  password:
    prefix: identification
    suffix: bob

knife4j:
  enable: true
  setting:
    language: zh-CN

#rabbitmq:
#  host: localhost # rabbitmq的连接地址
#  port: 5672 # rabbitmq的连接端口号
#  virtual-host: /identification # rabbitmq的虚拟host
#  username: littlebob # rabbitmq的用户名
#  password: wsd2586 # rabbitmq的密码
#  publisher-confirms: true #如果对异步消息需要回调必须设置为true

logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.bob.identification: debug
    com.bob.identification.*.mapper: debug
  config: classpath:logback-spring.xml